#!/usr/bin/perl -tw

use lib qw(t/lib);
use Test::More tests => 1;

my $warnings = '';
{
    local $SIG{__WARN__} = sub { $warnings .= join '', @_ };
    `$^X $0`;
}
like( $warnings, '/^Insecure dependency/', '-t honored' );
